require 'rails_helper'

describe Sheet do
  
  it { should validate_presence_of(:name) }
  # it { should validate_presence_of(:round1g1a) }
  # it { should validate_presence_of(:round1g2a) }
  # it { should validate_presence_of(:round1g3a) }
  # it { should validate_presence_of(:round1g4a) }
  # it { should validate_presence_of(:round1g5a) }
  # it { should validate_presence_of(:round1g6a) }
  # it { should validate_presence_of(:round1g7a) }
  # it { should validate_presence_of(:round1g8a) }
  # it { should validate_presence_of(:round1g9a) }
  # it { should validate_presence_of(:round1g10a) }
  # it { should validate_presence_of(:round1g11a) }
  # it { should validate_presence_of(:round1g12a) }
  # it { should validate_presence_of(:round1g13a) }
  # it { should validate_presence_of(:round1g14a) }
  # it { should validate_presence_of(:round1g15a) }
  # it { should validate_presence_of(:round1g16a) }
  # it { should validate_presence_of(:round1g1b) }
  # it { should validate_presence_of(:round1g2b) }
  # it { should validate_presence_of(:round1g3b) }
  # it { should validate_presence_of(:round1g4b) }
  # it { should validate_presence_of(:round1g5b) }
  # it { should validate_presence_of(:round1g6b) }
  # it { should validate_presence_of(:round1g7b) }
  # it { should validate_presence_of(:round1g8b) }
  # it { should validate_presence_of(:round1g9b) }
  # it { should validate_presence_of(:round1g10b) }
  # it { should validate_presence_of(:round1g11b) }
  # it { should validate_presence_of(:round1g12b) }
  # it { should validate_presence_of(:round1g13b) }
  # it { should validate_presence_of(:round1g14b) }
  # it { should validate_presence_of(:round1g15b) }
  # it { should validate_presence_of(:round1g16b) }
  # it { should validate_presence_of(:round2g1a) }
  # it { should validate_presence_of(:round2g2a) }
  # it { should validate_presence_of(:round2g3a) }
  # it { should validate_presence_of(:round2g4a) }
  # it { should validate_presence_of(:round2g5a) }
  # it { should validate_presence_of(:round2g6a) }
  # it { should validate_presence_of(:round2g7a) }
  # it { should validate_presence_of(:round2g8a) }
  # it { should validate_presence_of(:round2g1b) }
  # it { should validate_presence_of(:round2g2b) }
  # it { should validate_presence_of(:round2g3b) }
  # it { should validate_presence_of(:round2g4b) }
  # it { should validate_presence_of(:round2g5b) }
  # it { should validate_presence_of(:round2g6b) }
  # it { should validate_presence_of(:round2g7b) }
  # it { should validate_presence_of(:round2g8b) }
  # it { should validate_presence_of(:round3g1a) }
  # it { should validate_presence_of(:round3g2a) }
  # it { should validate_presence_of(:round3g3a) }
  # it { should validate_presence_of(:round3g4a) }
  # it { should validate_presence_of(:round3g1b) }
  # it { should validate_presence_of(:round3g2b) }
  # it { should validate_presence_of(:round3g3b) }
  # it { should validate_presence_of(:round3g4b) }
  # it { should validate_presence_of(:round4g1) }
  # it { should validate_presence_of(:round4g2) }
  # it { should validate_presence_of(:round4g3) }
  # it { should validate_presence_of(:round4g4) }
  # it { should validate_presence_of(:round5g1) }
  # it { should validate_presence_of(:round5g2) }
  # it { should validate_presence_of(:round6) }
end